### ISSUE TITLE
Trash bin marker tracking

### ISSUE THREAD

**Issue by mangoglass** [mangoglass/AgeOfGarb#18]
We need implementation that makes our AR system recognize some specific markings that are to be placed at the top and bottom of the physical trash bins that we are to 3d print. 

The marking should specifically be a top marking and a bottom marking. The game should be able to tell if a trash bin is held upside down or not by looking at these marking. It should also include the ability to rotate or tilt the trash bins based on how it sees the markings. 

The marking itself can be whatever works the best, it doesn't have to look a specific way. A starting point could be markings that look like [this](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F8a%2Fa0%2F05%2F8aa00528c91b6443d59ad55daa130e98.jpg&f=1&nofb=1).

- [ ] Can tilt and rotate based on marking.
- [ ] Understands top and bottom markings.

**Comment by aog9128** [comment]
Maybe we should remove this issue after our talk with Mario.

**Comment by mangoglass** [comment]
You're right @aog9128. Will transfer over neccessary functionality to the other tracker issue #42
